### ISSUE TITLE
there is a bug in matrix absSum()

### ISSUE THREAD

**Issue by lucineIT** [midjji/lambdatwist-p3p#1]
T absSum(){
        const Matrix& A = *this;
        T absv=std::abs(A(0));

        for(unsigned int i=1;i<Rows*Cols;++i)
            absv=+std::abs(A(i));
        return absv;
    }

absv is the only the last element in the matrix,how it work correct?
there are also a problem in the paper, near the equation (16) ,the compute fo lambda is not correctly

**Comment by midjji** [comment]
Hi lucineIT,

absv is initialized to the first value of A,
and then incremented by the value of every index in A before being
returned.
absv=+std::abs(A(i)); note the +=
The matrix library is well covered by unit tests including abssum.

Regarding the paper:
I know there is an error in equation 3 which should read:
λ^2_i + λ^2_j − 2bijλ_iλ_j = aij ,
And also in the text above equation 16 which should read:
LM_23L=a_23. Not LM_23L=a_12
as well as below 16, where 1+t(t+b) which should be:
1+t(t-2b) which is then not always positive, by the reasoning mentioned,
complex solutions can result from numerical errors as well however and are
checked for and discarded as infeasible regardless. (If I remember
correctly)
equation 16 however is correct as far as I can tell.

I really should make and updated version on arxiv, the camera ready work
was a bit rushed, sorry about that.

 thank you for pointing this out.

**Comment by midjji** [comment]
No you are right, there is an error in abssum!
Damned unit test was wrong.
Jikes, I rerunning and checking.

**Comment by midjji** [comment]
Fixed both, pushed and reran all tests and the benchmark, 
The result holds with no significant difference.

**Comment by lucineIT** [comment]
ok, thanks for your replay.
