### ISSUE TITLE
Possible bug in refine_lambda.h

### ISSUE THREAD

**Issue by jremington** [midjji/lambdatwist-p3p#2]
There is a curious comment in refine_lambda.h about the routine sometimes failing "for unknown reasons" in cases of incorrect solutions. 

I suspect that at least one problem is in the step where the new L (L1) is generated, and a new step computed for testing the step.

Surely the following test should be using L1() instead of L()!
`               T l1=L(0);
                T l2=L(1);
                T l3=L(2);
                T r11=l1*l1 + l2*l2 +b12*l1*l2 -a12;
                T r12=l1*l1 + l3*l3 +b13*l1*l3 -a13;
                T r13=l2*l2 + l3*l3 +b23*l2*l3 -a23;
                if(std::abs(r11) +std::abs(r12) + std::abs(r13)>std::abs(r1) +std::abs(r2) +std::abs(r3)){
                    // cout<<"bad step: "<< det*(Ji*r)<<++badsteps<<" "<< i<<endl;
                    break;`
Regards, Jim Remington

**Comment by midjji** [comment]
Thank you!
You are right that this is a bug and the test should be on L1. Fixing this improves speed 20% but drops accuracy on the correct solution, losing 5 solutions. Basically taking bad steps is sometimes required for convergence in the numerically worst cases. Its tricky, better nl solvers have the disturbing tendency to incorrectly? reduce the number of unique solutions. The correct solution is never removed though. 

I havent decided how to fix it yet, so I'll leave this issue open till tomorrow.

**Comment by midjji** [comment]
A few more experiments show that for other computers and more samples the effect is positive on average. Meaning there is only speed gain, I've pushed the fix.

**Comment by midjji** [comment]
The error referred to in the comment is that the correct solution is always improved, but incorrect but valid solutions can be lost in near degenerate cases. 

Also this code can be improved further, working on that.
