### ISSUE TITLE
solve transformation by p3p

### ISSUE THREAD

**Issue by yuyadanyadan** [midjji/lambdatwist-p3p#3]
It is not stable when  solve transformation by kneip p3p method

**Comment by midjji** [comment]
???

This is a benchmark comparison of the original authors (knep in this case)
implementations of different p3p methods. And yes, kneips method is not
stable. Lambdatwist is orders of magnitude better.

The repo is only for replication of an experiment, use midjji/PNP which is
based on lambdatwist if you want a p3p solver.
